#!/bin/sh

set -e
ARCH=`dpkg --print-architecture`
V=`php -v | head -1 | awk {'print $2'} | cut -c 1-3`
IONPATH=/usr/share/ioncube/${ARCH}/ioncube_loader_lin_${V}.so


case "$1" in
    configure)
        echo zend_extension= > /etc/php5/mods-available/ioncube.ini

        sed -i /etc/php5/mods-available/ioncube.ini -e "s:zend_extension=:zend_extension=${IONPATH}:"

        if [ -d "/etc/php5/apache2/" ]; then

            if [ ! -f "/etc/php5/apache2/conf.d/01-ioncube.ini" ]; then
                ln -s /etc/php5/mods-available/ioncube.ini /etc/php5/apache2/conf.d/01-ioncube.ini
             fi
        fi

        if [ -d "/etc/php5/cli/" ]; then
            if [ ! -f "/etc/php5/cli/conf.d/01-ioncube.ini" ]; then
                ln -s /etc/php5/mods-available/ioncube.ini /etc/php5/cli/conf.d/01-ioncube.ini
            fi
        fi

        if [ -d "/etc/php5/fpm/" ]; then
            if [ ! -f "/etc/php5/fpm/conf.d/01-ioncube.ini" ]; then
                ln -s /etc/php5/mods-available/ioncube.ini /etc/php5/fpm/conf.d/01-ioncube.ini
            fi
        fi
    ;;

    triggered)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        rm /etc/php5/apache2/conf.d/01-ioncube.ini
        rm /etc/php5/apache2/conf.d/01-ioncube.ini
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

